# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '6.x'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: $(Build.SourcesDirectory)

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debug'

# ------- No Tests to run in this project 
# - task: VSTest@2
#   displayName: "Run unit tests in the project"  
#   inputs:   
#     testSelector: "testAssemblies"    
#     searchFolder: '$(System.DefaultWorkingDirectory)'    
#     resultsFolder: '$(Agent.TempDirectory)\TestResults'    
#     codeCoverageEnabled: True    
#     publishRunAttachments: true 

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifact-drop' # string. Required. Artifact name. Default: drop.
    publishLocation: 'Container'
